import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from '@playwright/test';
const base=process.env.SITE_URL;assert.ok(base,'Set SITE_URL to the Concept 2 preview.');
const browser=await chromium.launch({headless:true,channel:process.env.UI_BROWSER_CHANNEL||'msedge'});
try{await mkdir('.qa',{recursive:true});const page=await browser.newPage({viewport:{width:1366,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',error=>errors.push(error.message));const response=await page.goto(base,{waitUntil:'networkidle'});assert.equal(response.status(),200);
 const pixels=await page.evaluate(async()=>{const load=async src=>{const img=new Image();img.src=src;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);return {width:canvas.width,height:canvas.height,data:ctx.getImageData(0,0,canvas.width,canvas.height).data}};const old=await load('/images/cleanest-logo.jpeg'),logo=await load('/images/cleanest-logo-transparent.webp'),icon=await load('/favicon.png');let preserved=0,softEdges=0,whiteDetails=0;for(let i=0;i<logo.data.length;i+=4){if(logo.data[i+3]===255){if(old.data[i]!==logo.data[i]||old.data[i+1]!==logo.data[i+1]||old.data[i+2]!==logo.data[i+2])throw new Error('Opaque artwork pixel changed');preserved++;}else if(logo.data[i+3]>0)softEdges++;if(old.data[i]>220&&old.data[i+1]>220&&old.data[i+2]>220){if(logo.data[i+3]!==255)throw new Error('White lettering lost opacity');whiteDetails++;}}return {width:logo.width,height:logo.height,originalWidth:old.width,originalHeight:old.height,preserved,softEdges,whiteDetails,corners:[0,logo.width-1,(logo.height-1)*logo.width,logo.width*logo.height-1].map(i=>logo.data[i*4+3]),faviconCorner:icon.data[3],faviconWidth:icon.width,faviconHeight:icon.height}});
 assert.equal(pixels.width,pixels.originalWidth);assert.equal(pixels.height,pixels.originalHeight);assert.deepEqual(pixels.corners,[0,0,0,0]);assert.equal(pixels.faviconCorner,0);assert.ok(pixels.preserved>700000);assert.ok(pixels.whiteDetails>30000);assert.ok(pixels.softEdges>1000);assert.equal(pixels.faviconWidth/pixels.faviconHeight,pixels.width/pixels.height);
 assert.equal(await page.locator('link[rel="icon"]').getAttribute('href'),'/favicon.png');assert.match(await page.locator('meta[name=robots]').getAttribute('content'),/noindex/);if(base.startsWith('https:'))assert.match(response.headers()['x-robots-tag'],/noindex/);
 for(const width of [320,375,430,768,1366,1920]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>scrollTo(0,0));const size=await page.locator('.site-header .logo img').evaluate(image=>{const rect=image.getBoundingClientRect();return {ratio:rect.width/rect.height,src:image.getAttribute('src')}});assert.equal(size.src,'/images/cleanest-logo-transparent.webp');assert.ok(Math.abs(size.ratio-pixels.width/pixels.height)<.001);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`.qa/transparent-header-${width}.png`});await page.evaluate(()=>scrollTo(0,700));await page.waitForTimeout(80);assert.ok(Math.abs(await page.locator('.site-header').evaluate(element=>element.getBoundingClientRect().top))<1,'Sticky header is pinned');await page.screenshot({path:`.qa/transparent-sticky-${width}.png`});}
 assert.deepEqual(errors,[]);console.log('PASS: original dimensions and opaque artwork pixels preserved, all white details intact, transparent corners and smooth alpha edges, proportional transparent favicon, six desktop/mobile/sticky header widths and noindex.');
}finally{await browser.close();}
