import { StrictMode, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ArrowUpRight, Check, ChevronLeft, ChevronRight, Leaf, MapPin, Menu, X, Phone, Sparkles, HeartHandshake, Building2, Waves, MessageCircle, Quote } from 'lucide-react';
import { areas, business, reviews, services } from './data';
import { Heading, Logo, Photo, QuoteButton } from './components';
import { QuoteForm } from './QuoteForm';
import './styles.css';

const navigation=[['Home','#home'],['Services','#services'],['About','#about'],['Our Work','#work'],['Areas We Serve','#areas'],['Contact','#contact']];
const gallery=[{file:'newuph1.webp',title:'Carpet care, up close',alt:'Cleanest staff member extracting dirt from a carpet, shown on the original Cleanest website',category:'Cleaning'},{file:'newgarden2.webp',title:'Keeping gardens in shape',alt:'Garden worker trimming a hedge, from Cleanest’s original garden gallery',category:'Gardens'},{file:'winc1.webp',title:'A clearer outlook',alt:'Window being cleaned with a squeegee, from Cleanest’s service gallery',category:'Cleaning'}];

function App(){
  const [menuOpen,setMenuOpen]=useState(false);
  const [selectedArea,setSelectedArea]=useState(0);
  const [location,setLocation]=useState('');
  const [service,setService]=useState('');
  const [reviewIndex,setReviewIndex]=useState(0);
  const [galleryFilter,setGalleryFilter]=useState('All');
  const menuButton=useRef<HTMLButtonElement>(null);
  const area=areas[selectedArea];
  const review=reviews[reviewIndex];
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'&&menuOpen){setMenuOpen(false);menuButton.current?.focus();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[menuOpen]);
  return <><a className="skip-link" href="#main">Skip to content</a><div className="utility-bar"><div className="wrap"><span><MapPin size={14}/>Johannesburg & Plettenberg Bay</span><div><a href={`tel:${business.tel}`}><Phone size={14}/>{business.phone}</a><a href={business.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={14}/>WhatsApp us<ArrowUpRight size={13}/></a></div></div></div><header className="site-header"><div className="wrap nav-row"><Logo/><nav id="main-navigation" className={menuOpen?'open':''} aria-label="Main navigation">{navigation.map(([title,href])=><a href={href} key={href} onClick={()=>setMenuOpen(false)}>{title}</a>)}</nav><QuoteButton className="header-quote"/><button ref={menuButton} className="menu-button" aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} aria-controls="main-navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div><div className="mobile-contacts"><a href={`tel:${business.tel}`}><Phone size={15}/>Call Cleanest</a><a href={business.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={16}/>WhatsApp us</a><a href="#contact" onClick={()=>setMenuOpen(false)}>Request a Quote<ArrowRight size={15}/></a></div></header>
    <main id="main"><section className="hero" id="home"><div className="hero-photo"><Photo file="newgarden1.webp" alt="Cleanest’s garden maintenance team working on a coastal lawn, from the existing Cleanest website" priority/><span className="hero-photo-note"><Leaf size={17}/>Fresh outdoors. Cared-for spaces.</span></div><div className="wrap hero-inner"><div className="hero-message"><span className="kicker"><span className="fresh-dot"/>CLEANING & GARDEN CARE</span><h1>A fresh start<br/>for your<br/><span>home & garden.</span></h1><p>Professional cleaning and garden care, with 29 years of experience helping homes and businesses feel fresh, inside and out.</p><div className="hero-places"><MapPin size={16}/>Johannesburg & Plettenberg Bay</div><div className="hero-actions"><QuoteButton/><a className="btn btn-white" href="#services">Explore Services<ArrowRight size={17}/></a></div><a className="hero-whatsapp" href={business.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={17}/>Let’s talk about your space<ArrowUpRight size={15}/></a></div></div></section>
    <div className="quick-trust"><div className="wrap"><div className="trust-years"><strong>29</strong><span>years of<br/>experience</span></div><div><HeartHandshake/><span>Owner managed.<br/><strong>Personally cared for.</strong></span></div><div><MapPin/><span>Johannesburg<br/>& Plettenberg Bay</span></div><div><Sparkles/><span>Cleaning inside.<br/><strong>Garden care outside.</strong></span></div></div></div>
    <section className="section wrap" id="services"><div className="section-top"><Heading kicker="A LITTLE HELP GOES A LONG WAY" title="Fresh spaces start here." text="One place for the cleaning and garden care your property needs."/><QuoteButton className="services-quote"/></div><div className="services-layout">{services.map((item,index)=><article key={item.id} id={item.id} className={`service-tile service-${item.id}`}><div className="service-photo"><Photo file={item.image} alt={item.alt}/><span className="service-icon">{index===2?<Leaf size={22}/>:<Sparkles size={22}/>}</span></div><div className="service-content"><span className="service-category">{index===2?'OUTDOOR CARE':'INDOOR CARE'}</span><h3>{item.name}</h3><p>{item.description}</p><ul>{item.details.map(detail=><li key={detail}><Check size={15}/>{detail}</li>)}</ul><QuoteButton onClick={()=>setService(item.name)} className="service-quote">Request a Quote</QuoteButton></div></article>)}</div><div className="services-extra"><Leaf size={19}/><p>Garden care for complexes, estates, schools and sports fields, too.</p><a href="#contact" onClick={()=>setService('Garden services')}>Tell us what you need<ArrowRight size={17}/></a></div></section>
    <section className="about-section" id="about"><div className="section wrap about-layout"><div className="about-visual"><Photo file="carpetteam.webp" alt="Cleanest team pictured together in branded workwear alongside company vehicles, from Cleanest’s website"/><div className="about-photo-caption"><HeartHandshake size={20}/><span>Local teams. Personal attention.</span></div></div><div className="about-copy"><Heading kicker="HELLO, WE’RE CLEANEST" title="People who care for the places you care about."/><p>Cleanest brings professional cleaning and garden care to homes and businesses in Johannesburg and Plettenberg Bay.</p><p>With an owner-managed approach and dedicated local teams, personal attention is part of how we care for your property.</p><div className="about-points"><span><Check/>Carpets, upholstery & windows</span><span><Check/>Year-round garden maintenance</span><span><Check/>Homes, complexes & corporate grounds</span></div><QuoteButton/></div></div></section>
    <section className="section wrap" id="work"><div className="section-top"><Heading kicker="CLEANEST IN ACTION" title="A closer look at the care." text="Cleaning and garden imagery from Cleanest’s existing website."/><div className="gallery-filters" role="group" aria-label="Gallery category">{['All','Cleaning','Gardens'].map(category=><button key={category} aria-pressed={category===galleryFilter} onClick={()=>setGalleryFilter(category)}>{category}</button>)}</div></div><div className={`work-grid filter-${galleryFilter.toLowerCase()}`}>{gallery.filter(item=>galleryFilter==='All'||item.category===galleryFilter).map(item=><figure className="work-photo" key={item.file}><Photo file={item.file} alt={item.alt}/><figcaption><span>{item.category}</span><strong>{item.title}</strong></figcaption></figure>)}</div></section>
    <section className="area-section" id="areas"><div className="section wrap"><Heading kicker="LOCAL CARE. TWO PLACES TO CALL HOME." title="Find your Cleanest team." text="Select your location to explore the areas listed on our website." center/><div className="area-tabs" role="tablist" aria-label="Cleanest service locations">{areas.map((item,index)=><button key={item.name} id={`area-tab-${index}`} role="tab" aria-selected={selectedArea===index} aria-controls="area-panel" tabIndex={selectedArea===index?0:-1} onClick={()=>setSelectedArea(index)} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?1:1-selectedArea;setSelectedArea(next);document.getElementById(`area-tab-${next}`)?.focus();}}}>{index===0?<Building2 size={20}/>:<Waves size={22}/>} {item.name}</button>)}</div><div className="area-panel" id="area-panel" role="tabpanel" aria-labelledby={`area-tab-${selectedArea}`}><div className="area-identity"><div className="area-symbol">{selectedArea===0?<Building2 size={64} strokeWidth={1.2}/>:<Waves size={64} strokeWidth={1.2}/>}</div><span>{area.label}</span><h3>{area.name}</h3><p>{area.description}</p><QuoteButton onClick={()=>setLocation(area.name)}>Request a Quote</QuoteButton></div><div className="area-suburbs"><h4>Is your area here?</h4><p>Service areas listed by Cleanest:</p><div className="suburb-list">{area.suburbs.split(' · ').map(suburb=><span key={suburb}><MapPin size={13}/>{suburb}</span>)}</div><a href="#contact" onClick={()=>setLocation(area.name)}>Ask us about your suburb<ArrowRight size={17}/></a></div></div></div></section>
    <section className="reviews-section" id="reviews"><div className="wrap review-layout"><div className="review-title"><span className="kicker">FROM OUR CUSTOMERS</span><h2>Fresh spaces.<br/>Happy words.</h2><div className="review-controls"><button onClick={()=>setReviewIndex((reviewIndex+reviews.length-1)%reviews.length)} aria-label="Previous testimonial"><ChevronLeft/></button><span>{reviewIndex+1} / {reviews.length}</span><button onClick={()=>setReviewIndex((reviewIndex+1)%reviews.length)} aria-label="Next testimonial"><ChevronRight/></button></div></div><figure className="customer-review" aria-live="polite"><Quote size={32} strokeWidth={1.3} aria-hidden="true"/><blockquote>{review.quote}</blockquote><figcaption><div className="customer-initials" aria-hidden="true">{review.name.split(' ').map(value=>value[0]).join('')}</div><div><strong>{review.name}</strong><span>{review.area}</span></div><a href={review.source} target="_blank" rel="noreferrer" aria-label={`Source testimonial for ${review.name}`}><ArrowUpRight size={20}/></a></figcaption></figure></div></section>
    <section className="quote-section" id="contact"><div className="section wrap"><Heading kicker="YOUR FRESH START" title="What can we take care of?" text="Choose your area, tell us about the work and add a few photos if you’d like." center/><QuoteForm location={location} setLocation={setLocation} service={service} setService={setService}/></div></section>
    </main><footer><div className="footer-banner"><div className="wrap"><div><Leaf size={28}/><strong>Inside. Outside. Cleanest.</strong></div><a href="#contact">Request a Quote<ArrowRight size={20}/></a></div></div><div className="wrap footer-main"><div className="footer-brand"><Logo/><p>Professional cleaning and garden care in Johannesburg & Plettenberg Bay.</p><a href={business.facebook} target="_blank" rel="noreferrer">Find us on Facebook<ArrowUpRight size={16}/></a></div><div><h3>Explore</h3>{navigation.slice(1).map(([name,href])=><a key={href} href={href}>{name}</a>)}</div><div><h3>Our services</h3>{services.map(item=><a key={item.id} href={`#${item.id}`}>{item.name}</a>)}</div><div><h3>Say hello</h3><a href={`tel:${business.tel}`}>{business.phone}</a>{business.emails.map(email=><a key={email} href={`mailto:${email}`}>{email}</a>)}<span>Mon–Fri · 08h00–17h00</span></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Cleanest. All rights reserved.</span><span>Johannesburg · Plettenberg Bay</span><a href="#home">Back to top ↑</a></div></footer></>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);

